version: 2
jobs:
  install:
    docker:
      - image: circleci/node:12
    working_directory: ~/tp
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/tp
    steps:
      - checkout
      - run : echo "run test"
      - run: npm test
workflows:
  version: 2
  deploy:
    jobs:
      - install
      - test:
          requires:
            - install

